apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  # Selectors are the smart way to do it, rather than making Endpoints explicit:
  selector:
    myname: rs01
  ports:
  # Port is the port service listens on
  # targetPort is the port that it feeds things to on pod/container:
  - port: 8080
    targetPort: 80

---
# This is kind of a bad way to do it... We're adding the IP
# of a specific pod.

apiVersion: v1
kind: Endpoints
metadata:
  name: simple-service
subsets:
  - addresses:
    - ip: 10.244.0.10
    ports:
      - port: 80
